export type NumberTriviaDifficulty = 'easy' | 'medium' | 'hard' | 'very-hard'

export interface NumberTriviaQuestion {
  prompt: string
  answer: number
  difficulty: NumberTriviaDifficulty
}

export const NUMBER_TRIVIA_QUESTIONS: NumberTriviaQuestion[] = [
  { prompt: 'How many minutes are in an hour?', answer: 60, difficulty: 'easy' },
  { prompt: 'How many days are in a week?', answer: 7, difficulty: 'easy' },
  { prompt: 'How many months are in a year?', answer: 12, difficulty: 'easy' },
  { prompt: 'How many hours are in a day?', answer: 24, difficulty: 'easy' },
  { prompt: 'How many seconds are in a minute?', answer: 60, difficulty: 'easy' },
  { prompt: 'How many legs does a spider have?', answer: 8, difficulty: 'easy' },
  { prompt: 'How many continents are there?', answer: 7, difficulty: 'easy' },
  { prompt: 'How many colors are in a rainbow?', answer: 7, difficulty: 'easy' },
  { prompt: 'How many sides does a triangle have?', answer: 3, difficulty: 'easy' },
  { prompt: 'How many sides does a square have?', answer: 4, difficulty: 'easy' },
  { prompt: 'How many fingers does a human have?', answer: 10, difficulty: 'easy' },
  { prompt: 'How many toes does a human have?', answer: 10, difficulty: 'easy' },
  { prompt: 'How many wheels does a bicycle have?', answer: 2, difficulty: 'easy' },
  {
    prompt: 'How many players in a football (soccer) team on the field?',
    answer: 11,
    difficulty: 'easy',
  },
  { prompt: 'How many letters are in the English alphabet?', answer: 26, difficulty: 'easy' },
  { prompt: 'How many days in a leap year?', answer: 366, difficulty: 'easy' },
  { prompt: 'How many zeros in 100?', answer: 2, difficulty: 'easy' },
  { prompt: 'How many weeks in a year (approx)?', answer: 52, difficulty: 'easy' },
  { prompt: 'How many months have 31 days?', answer: 7, difficulty: 'easy' },
  { prompt: 'How many primary colors are there?', answer: 3, difficulty: 'easy' },
  { prompt: 'How many planets in the Solar System?', answer: 8, difficulty: 'easy' },
  { prompt: 'How many seasons in a year?', answer: 4, difficulty: 'easy' },
  { prompt: 'How many eyes does a typical human have?', answer: 2, difficulty: 'easy' },
  { prompt: 'How many hours in half a day?', answer: 12, difficulty: 'easy' },
  { prompt: 'How many minutes in half an hour?', answer: 30, difficulty: 'easy' },
  { prompt: 'How many sides does a pentagon have?', answer: 5, difficulty: 'easy' },
  { prompt: 'How many sides does a hexagon have?', answer: 6, difficulty: 'easy' },
  { prompt: 'How many vowels in English?', answer: 5, difficulty: 'easy' },
  { prompt: 'How many days in April?', answer: 30, difficulty: 'easy' },
  { prompt: 'How many cards in a standard deck?', answer: 52, difficulty: 'easy' },
  { prompt: 'How many suits in cards?', answer: 4, difficulty: 'easy' },
  { prompt: 'How many players in a basketball team on court?', answer: 5, difficulty: 'easy' },
  { prompt: 'How many players in a volleyball team on court?', answer: 6, difficulty: 'easy' },
  { prompt: 'How many days in February (non-leap)?', answer: 28, difficulty: 'easy' },
  { prompt: 'How many hours in 2 days?', answer: 48, difficulty: 'easy' },
  { prompt: 'How many minutes in 2 hours?', answer: 120, difficulty: 'easy' },
  { prompt: 'How many seconds in 2 minutes?', answer: 120, difficulty: 'easy' },
  { prompt: 'How many days in 2 weeks?', answer: 14, difficulty: 'easy' },
  { prompt: 'How many months in 2 years?', answer: 24, difficulty: 'easy' },
  { prompt: 'How many sides does an octagon have?', answer: 8, difficulty: 'easy' },
  { prompt: 'How many weeks in a month (approx)?', answer: 4, difficulty: 'easy' },
  { prompt: 'How many legs does a dog have?', answer: 4, difficulty: 'easy' },
  { prompt: 'How many legs does an insect have?', answer: 6, difficulty: 'easy' },
  { prompt: "How many letters in 'CAT'?", answer: 3, difficulty: 'easy' },
  { prompt: 'How many numbers in a dozen?', answer: 12, difficulty: 'easy' },
  { prompt: 'How many days in a weekend?', answer: 2, difficulty: 'easy' },
  { prompt: 'How many digits in base-10 system?', answer: 10, difficulty: 'easy' },
  { prompt: 'How many centimeters in a meter?', answer: 100, difficulty: 'easy' },
  { prompt: 'How many meters in a kilometer?', answer: 1000, difficulty: 'easy' },
  { prompt: 'How many grams in a kilogram?', answer: 1000, difficulty: 'easy' },
  { prompt: 'How many states are in the USA?', answer: 50, difficulty: 'medium' },
  { prompt: 'How many countries are in the EU (2026)?', answer: 27, difficulty: 'medium' },
  { prompt: 'How many bones in the adult human body?', answer: 206, difficulty: 'medium' },
  {
    prompt: 'How many players in an American football team on field?',
    answer: 11,
    difficulty: 'medium',
  },
  { prompt: 'How many time zones are there worldwide?', answer: 24, difficulty: 'medium' },
  { prompt: 'How many squares on a chessboard?', answer: 64, difficulty: 'medium' },
  { prompt: 'How many Grand Slam tournaments in tennis?', answer: 4, difficulty: 'medium' },
  { prompt: 'How many planets are classified as gas giants?', answer: 4, difficulty: 'medium' },
  { prompt: 'How many rings are on the Olympic flag?', answer: 5, difficulty: 'medium' },
  { prompt: 'How many days are in a year exactly (non leap)?', answer: 365, difficulty: 'medium' },
  { prompt: 'How many keys on a standard piano?', answer: 88, difficulty: 'medium' },
  {
    prompt: 'How many elements in the periodic table (approx)?',
    answer: 118,
    difficulty: 'medium',
  },
  { prompt: 'How many strings does a standard guitar have?', answer: 6, difficulty: 'medium' },
  { prompt: 'How many continents border the Pacific Ocean?', answer: 5, difficulty: 'medium' },
  { prompt: 'How many moons does Mars have?', answer: 2, difficulty: 'medium' },
  { prompt: 'How many sides does a dodecagon have?', answer: 12, difficulty: 'medium' },
  { prompt: 'How many provinces are there in Canada?', answer: 10, difficulty: 'medium' },
  { prompt: 'How many timeouts per team in NBA game (standard)?', answer: 7, difficulty: 'medium' },
  { prompt: 'How many innings in a baseball game?', answer: 9, difficulty: 'medium' },
  { prompt: 'How many judges in the US Supreme Court?', answer: 9, difficulty: 'medium' },
  { prompt: 'How many sides does a cube have?', answer: 6, difficulty: 'medium' },
  { prompt: 'How many liters in a cubic meter?', answer: 1000, difficulty: 'medium' },
  { prompt: 'How many chromosomes in a human cell?', answer: 46, difficulty: 'medium' },
  { prompt: 'How many players in a cricket team?', answer: 11, difficulty: 'medium' },
  { prompt: 'How many countries are in Africa (approx)?', answer: 54, difficulty: 'medium' },
  { prompt: 'In which year did World War I begin?', answer: 1914, difficulty: 'hard' },
  { prompt: 'In which year did World War II end?', answer: 1945, difficulty: 'hard' },
  { prompt: 'In which year was the UN founded?', answer: 1945, difficulty: 'hard' },
  { prompt: 'In which year did the Berlin Wall fall?', answer: 1989, difficulty: 'hard' },
  { prompt: 'In which year was the first iPhone released?', answer: 2007, difficulty: 'hard' },
  { prompt: 'In which year did the Titanic sink?', answer: 1912, difficulty: 'hard' },
  { prompt: 'In which year did Bulgaria join the EU?', answer: 2007, difficulty: 'hard' },
  { prompt: 'In which year did man first go to space?', answer: 1961, difficulty: 'hard' },
  { prompt: 'In which year did the first email get sent?', answer: 1971, difficulty: 'hard' },
  { prompt: 'In which year was DNA structure discovered?', answer: 1953, difficulty: 'hard' },
  { prompt: 'In which year did the Chernobyl disaster occur?', answer: 1986, difficulty: 'hard' },
  { prompt: 'In which year was Google founded?', answer: 1998, difficulty: 'hard' },
  { prompt: 'In which year did Facebook launch?', answer: 2004, difficulty: 'hard' },
  {
    prompt: 'In which year did the Euro become physical currency?',
    answer: 2002,
    difficulty: 'hard',
  },
  { prompt: 'In which year did the Soviet Union collapse?', answer: 1991, difficulty: 'hard' },
  {
    prompt: 'In which year did humans first land on the Moon?',
    answer: 1969,
    difficulty: 'very-hard',
  },
  {
    prompt: 'In which year was the first successful heart transplant?',
    answer: 1967,
    difficulty: 'very-hard',
  },
  { prompt: 'In which year was CRISPR discovered?', answer: 2012, difficulty: 'very-hard' },
  {
    prompt: 'In which year was the first vaccine developed?',
    answer: 1796,
    difficulty: 'very-hard',
  },
  {
    prompt: 'In which year did the first computer virus appear?',
    answer: 1971,
    difficulty: 'very-hard',
  },
  {
    prompt: 'In which year was the first Nobel Prize awarded?',
    answer: 1901,
    difficulty: 'very-hard',
  },
  { prompt: 'In which year was penicillin discovered?', answer: 1928, difficulty: 'very-hard' },
  {
    prompt: 'In which year was the first photograph taken?',
    answer: 1826,
    difficulty: 'very-hard',
  },
  { prompt: 'In which year did the first airplane fly?', answer: 1903, difficulty: 'very-hard' },
  {
    prompt: 'In which year was the internet (ARPANET) created?',
    answer: 1969,
    difficulty: 'very-hard',
  },
  {
    prompt: 'In which year did the first human genome get sequenced?',
    answer: 2003,
    difficulty: 'very-hard',
  },
  {
    prompt: 'In which year did the first IVF baby get born?',
    answer: 1978,
    difficulty: 'very-hard',
  },
  {
    prompt: 'In which year did the first nuclear reactor operate?',
    answer: 1942,
    difficulty: 'very-hard',
  },
  {
    prompt: 'In which year did the first mobile phone call happen?',
    answer: 1973,
    difficulty: 'very-hard',
  },
  {
    prompt: 'In which year did the first satellite launch?',
    answer: 1957,
    difficulty: 'very-hard',
  },
]
