/**
 * wildcardWesternQuestions.ts – Question bank for Wildcard Western.
 */

export interface WildcardQuestion {
  id: string
  prompt: string
  options: [string, string, string]
  correctIndex: 0 | 1 | 2
  difficulty: 'easy' | 'medium' | 'hard'
  category: string
}

export const WILDCARD_QUESTIONS: WildcardQuestion[] = [
  {
    id: 'q001',
    prompt: 'Which planet is known as the Red Planet?',
    options: ['Venus', 'Mars', 'Jupiter'],
    correctIndex: 1,
    difficulty: 'easy',
    category: 'Science',
  },
  {
    id: 'q002',
    prompt: 'What is the capital of France?',
    options: ['Berlin', 'Madrid', 'Paris'],
    correctIndex: 2,
    difficulty: 'easy',
    category: 'Geography',
  },
  {
    id: 'q003',
    prompt: 'Who painted the Mona Lisa?',
    options: ['Leonardo da Vinci', 'Michelangelo', 'Raphael'],
    correctIndex: 0,
    difficulty: 'easy',
    category: 'Art',
  },
  {
    id: 'q004',
    prompt: 'What is the largest ocean on Earth?',
    options: ['Atlantic', 'Indian', 'Pacific'],
    correctIndex: 2,
    difficulty: 'easy',
    category: 'Geography',
  },
  {
    id: 'q005',
    prompt: 'How many continents are there?',
    options: ['5', '7', '9'],
    correctIndex: 1,
    difficulty: 'easy',
    category: 'Geography',
  },
  {
    id: 'q006',
    prompt: 'What is the smallest prime number?',
    options: ['0', '1', '2'],
    correctIndex: 2,
    difficulty: 'easy',
    category: 'Math',
  },
  {
    id: 'q007',
    prompt: 'Which animal is known as the King of the Jungle?',
    options: ['Tiger', 'Lion', 'Elephant'],
    correctIndex: 1,
    difficulty: 'easy',
    category: 'Nature',
  },
  {
    id: 'q008',
    prompt: 'What is the chemical symbol for gold?',
    options: ['Go', 'Gd', 'Au'],
    correctIndex: 2,
    difficulty: 'medium',
    category: 'Science',
  },
  {
    id: 'q009',
    prompt: 'How many sides does a hexagon have?',
    options: ['5', '6', '7'],
    correctIndex: 1,
    difficulty: 'easy',
    category: 'Math',
  },
  {
    id: 'q010',
    prompt: 'Who wrote "Romeo and Juliet"?',
    options: ['Charles Dickens', 'William Shakespeare', 'Jane Austen'],
    correctIndex: 1,
    difficulty: 'easy',
    category: 'Literature',
  },
  {
    id: 'q011',
    prompt: 'What is the hardest natural substance on Earth?',
    options: ['Gold', 'Iron', 'Diamond'],
    correctIndex: 2,
    difficulty: 'medium',
    category: 'Science',
  },
  {
    id: 'q012',
    prompt: 'In which year did World War II end?',
    options: ['1943', '1945', '1947'],
    correctIndex: 1,
    difficulty: 'medium',
    category: 'History',
  },
  {
    id: 'q013',
    prompt: 'What is the capital of Japan?',
    options: ['Seoul', 'Beijing', 'Tokyo'],
    correctIndex: 2,
    difficulty: 'easy',
    category: 'Geography',
  },
  {
    id: 'q014',
    prompt: 'How many bones are in the adult human body?',
    options: ['186', '206', '226'],
    correctIndex: 1,
    difficulty: 'medium',
    category: 'Science',
  },
  {
    id: 'q015',
    prompt: 'What is the largest mammal in the world?',
    options: ['African Elephant', 'Blue Whale', 'Giraffe'],
    correctIndex: 1,
    difficulty: 'easy',
    category: 'Nature',
  },
  {
    id: 'q016',
    prompt: 'Which country is known as the Land of the Rising Sun?',
    options: ['China', 'Japan', 'Thailand'],
    correctIndex: 1,
    difficulty: 'easy',
    category: 'Geography',
  },
  {
    id: 'q017',
    prompt: 'What is the square root of 144?',
    options: ['10', '12', '14'],
    correctIndex: 1,
    difficulty: 'easy',
    category: 'Math',
  },
  {
    id: 'q018',
    prompt: 'Who was the first President of the United States?',
    options: ['Thomas Jefferson', 'George Washington', 'Abraham Lincoln'],
    correctIndex: 1,
    difficulty: 'easy',
    category: 'History',
  },
  {
    id: 'q019',
    prompt: 'What is the main ingredient in guacamole?',
    options: ['Tomato', 'Avocado', 'Pepper'],
    correctIndex: 1,
    difficulty: 'easy',
    category: 'Food',
  },
  {
    id: 'q020',
    prompt: 'How many strings does a standard guitar have?',
    options: ['4', '6', '8'],
    correctIndex: 1,
    difficulty: 'easy',
    category: 'Music',
  },
  {
    id: 'q021',
    prompt: 'What is the speed of light in vacuum (approximately)?',
    options: ['300,000 km/s', '150,000 km/s', '500,000 km/s'],
    correctIndex: 0,
    difficulty: 'medium',
    category: 'Science',
  },
  {
    id: 'q022',
    prompt: 'Which planet is closest to the Sun?',
    options: ['Mercury', 'Venus', 'Earth'],
    correctIndex: 0,
    difficulty: 'easy',
    category: 'Science',
  },
  {
    id: 'q023',
    prompt: 'What is the largest desert in the world?',
    options: ['Sahara', 'Arabian', 'Antarctic'],
    correctIndex: 2,
    difficulty: 'hard',
    category: 'Geography',
  },
  {
    id: 'q024',
    prompt: 'Who painted "The Starry Night"?',
    options: ['Claude Monet', 'Vincent van Gogh', 'Pablo Picasso'],
    correctIndex: 1,
    difficulty: 'medium',
    category: 'Art',
  },
  {
    id: 'q025',
    prompt: 'What is the chemical formula for water?',
    options: ['H2O', 'CO2', 'O2'],
    correctIndex: 0,
    difficulty: 'easy',
    category: 'Science',
  },
  {
    id: 'q026',
    prompt: 'How many years are in a decade?',
    options: ['5', '10', '20'],
    correctIndex: 1,
    difficulty: 'easy',
    category: 'General',
  },
  {
    id: 'q027',
    prompt: 'What is the tallest mountain in the world?',
    options: ['K2', 'Everest', 'Kilimanjaro'],
    correctIndex: 1,
    difficulty: 'easy',
    category: 'Geography',
  },
  {
    id: 'q028',
    prompt: 'Which organ in the human body filters blood?',
    options: ['Liver', 'Kidney', 'Heart'],
    correctIndex: 1,
    difficulty: 'medium',
    category: 'Science',
  },
  {
    id: 'q029',
    prompt: 'What is the currency of the United Kingdom?',
    options: ['Euro', 'Pound', 'Dollar'],
    correctIndex: 1,
    difficulty: 'easy',
    category: 'Geography',
  },
  {
    id: 'q030',
    prompt: 'How many sides does a triangle have?',
    options: ['2', '3', '4'],
    correctIndex: 1,
    difficulty: 'easy',
    category: 'Math',
  },
  {
    id: 'q031',
    prompt: 'Who wrote "To Kill a Mockingbird"?',
    options: ['Harper Lee', 'Mark Twain', 'Ernest Hemingway'],
    correctIndex: 0,
    difficulty: 'medium',
    category: 'Literature',
  },
  {
    id: 'q032',
    prompt: 'What is the largest planet in our solar system?',
    options: ['Saturn', 'Jupiter', 'Neptune'],
    correctIndex: 1,
    difficulty: 'easy',
    category: 'Science',
  },
  {
    id: 'q033',
    prompt: 'In which continent is the Sahara Desert located?',
    options: ['Asia', 'Africa', 'Australia'],
    correctIndex: 1,
    difficulty: 'easy',
    category: 'Geography',
  },
  {
    id: 'q034',
    prompt: 'What does "HTTP" stand for?',
    options: [
      'HyperText Transfer Protocol',
      'High Transfer Text Protocol',
      'HyperText Translate Protocol',
    ],
    correctIndex: 0,
    difficulty: 'medium',
    category: 'Technology',
  },
  {
    id: 'q035',
    prompt: 'How many players are on a soccer team?',
    options: ['9', '11', '13'],
    correctIndex: 1,
    difficulty: 'easy',
    category: 'Sports',
  },
  {
    id: 'q036',
    prompt: 'What is the freezing point of water in Celsius?',
    options: ['-10°C', '0°C', '10°C'],
    correctIndex: 1,
    difficulty: 'easy',
    category: 'Science',
  },
  {
    id: 'q037',
    prompt: 'Which Shakespeare play features the characters Oberon and Titania?',
    options: ['Hamlet', "A Midsummer Night's Dream", 'Macbeth'],
    correctIndex: 1,
    difficulty: 'hard',
    category: 'Literature',
  },
  {
    id: 'q038',
    prompt: 'What is the longest river in the world?',
    options: ['Amazon', 'Nile', 'Yangtze'],
    correctIndex: 1,
    difficulty: 'medium',
    category: 'Geography',
  },
  {
    id: 'q039',
    prompt: 'How many colors are in a rainbow?',
    options: ['5', '7', '9'],
    correctIndex: 1,
    difficulty: 'easy',
    category: 'Science',
  },
  {
    id: 'q040',
    prompt: 'Who invented the telephone?',
    options: ['Thomas Edison', 'Alexander Graham Bell', 'Nikola Tesla'],
    correctIndex: 1,
    difficulty: 'medium',
    category: 'History',
  },
  {
    id: 'q041',
    prompt: 'What is the capital of Australia?',
    options: ['Sydney', 'Melbourne', 'Canberra'],
    correctIndex: 2,
    difficulty: 'medium',
    category: 'Geography',
  },
  {
    id: 'q042',
    prompt: 'How many minutes are in an hour?',
    options: ['50', '60', '70'],
    correctIndex: 1,
    difficulty: 'easy',
    category: 'General',
  },
]
